### ISSUE TITLE
missing link to merger tree poster

### ISSUE THREAD

**Issue by akcheung** [uwescience/myria-website#10]
http://db.cs.washington.edu/posters/MyMergerTree.pdf is broken link on http://myria.cs.washington.edu/projects.html

**Comment by jortiz16** [comment]
Thanks @akcheung ! @ljorr1 , do you have a copy of this poster we had at the website? I couldn't find a copy of it. I think you showed it in the mymergertree video. Thanks!

**Comment by ljorr1** [comment]
Fixed it. Thanks for pointing it out.
