### ISSUE TITLE
Subtree push

### ISSUE THREAD

**Issue by domoritz** [uwescience/myria-website#14]
So we can work on the documentation here and then push it to the right repository.

**Comment by dhutchis** [comment]
I looked at this and came across some problems.  The best solution I see is to recommend that people do not edit the subfolders in docs/ of the website repo.  The second best solution is the following as a script, using myria-web as an example child repo.
1. Clone myria-web in another folder.
2. Copy the current state of the website's docs/myria-web into the myria-web's docs/ repo.
3. Commit and push the changes in myria-web.

This strategy will result in the same change being duplicated when we run subtree-pull.sh.  I tried other strategies but they all resulted in suboptimal results, either merge conflicts or too much duplication.  

The limiting factor is that the "subtree" relationship is designed to be one way.  Website may contain part of myria-web as a subtree.  It is much harder to put the subtree in the website back into myria-web.  A further complicating factor is that we rename the paths from docs/ in myria-web to docs/myria-web in the website.

If we are on the same page to recommend that users do not edit the subfolders of docs/, then I will close this with a commit that adds a file `DO_NOT_EDIT_SUBFOLDERS_(files_here_are_ok)` inside docs/ of the website repo.

**Comment by domoritz** [comment]
Let's add a readme to the doc folder and close this issue.

**Comment by dhutchis** [comment]
Interesting use of the word "redeem".  Will do~

**Comment by domoritz** [comment]
Sorry, fixed. I wrote readme but my spell correction preferred redeem.

**Comment by dhutchis** [comment]
Funny, "redeem" could work in that context >.^)

**Comment by dhutchis** [comment]
Fixed by 1db27fcb13e10169277937f22d04b0281ae2b0c8
