### ISSUE TITLE
something wrong with vertical padding

### ISSUE THREAD

**Issue by dhalperi** [uwescience/myria-website#3]
When you click the links at the top the page jumps below the anchor link. This in turn makes the highlighting of the anchors "off" to user perception.

To reproduce:
1. load http://myria.cs.washington.edu/#people
2. scroll up a bit until you can see the "People" H1 tag
3. notice that the bar at the top does not show "People" highlighted any more, it switched to "Overview"

Something in my memory makes me think that vertical padding is the issue.

**Comment by domoritz** [comment]
I think Paris had a good point when he said we should have separate pages instead of weird scrolling.

**Comment by dhalperi** [comment]
Regardless, the overflow issue is likely in the base template and will affect any use of anchors in the entire website. Note that the direct link to the `#People` anchor is not, in fact, to the anchor.

**Comment by dhalperi** [comment]
(The link instead goes to what would be the `#people-faculty` anchor if we had sub-anchors.)

**Comment by domoritz** [comment]
Okay, there were two problems due to the fact that we have a fixed top bar. The browser tries to move the linked element to the top and the scrollspy assumes the same.

**Comment by dhalperi** [comment]
Very cool!
