### ISSUE TITLE
possible issue with padding at page bottom?

### ISSUE THREAD

**Issue by dhalperi** [uwescience/myria-website#5]
When I scroll all the way to the page bottom, the `Use Case Repository` section can fit entirely on my screen and is still not at the top.

![screen shot 2014-02-11 at 7 23 03 pm](https://f.cloud.github.com/assets/526415/2144915/072d7a66-9395-11e3-9f1f-be98abf0f326.png)

Yet, clicking the `Use Case Repository` label at the top makes the page scroll backwards.

![screen shot 2014-02-11 at 7 23 07 pm](https://f.cloud.github.com/assets/526415/2144916/0b373f5c-9395-11e3-8097-b489a922c3fd.png)

My guess is an issue with vertical padding at the bottom of the page.

**Comment by dhalperi** [comment]
Not fixed

**Comment by dhalperi** [comment]
FWICT same behavior despite changes from to #4

**Comment by domoritz** [comment]
![screen shot 2014-02-11 at 22 23 58](https://f.cloud.github.com/assets/589034/2145773/53844548-93ae-11e3-818f-b640dad6ea0f.PNG)

**Comment by dhalperi** [comment]
Should be able to see footer

**Comment by dhalperi** [comment]
Or rather, that's what I expect!

**Comment by dhalperi** [comment]
(The Acknowledgments link now has the error)

**Comment by domoritz** [comment]
The error and the fact that you can't see the footer come from the offset.

I don't consider this to be an error. More a not optimal position.

**Comment by dhalperi** [comment]
The whitespace between Acks and footer should be gone. When you click Acks, you should see the footer.

See http://dhalperi.github.io/linux-80211n-csitool/#authors for an example -- authors is not at the top of the page, but that's because the page is scrolled to the bottom.

When I click Acks, neither are we scrolled to the bottom NOR is Acks at the top of the page.

**Comment by domoritz** [comment]
Yes, because the page doesn't move you up by an offset once you reached your target.

``` js
      var offset = 79;
      $('.navbar-nav>li>a').click(function(event) {
        // fix scroll if link to main page
        var el = $(this);
        var a = document.createElement('a');
        a.href = el.attr('href');
        // only do this when we are on the root side
        if (a.pathname === $(location).attr('pathname')) {
          event.preventDefault();
          $(el.attr('data-target'))[0].scrollIntoView();
          scrollBy(0, -offset);
        };
      });
```

I could hack something to not do this for the last link but that would not work if you go to the item using a hash and also not update the scrollspy (because of the offset). I think the current state is the best i can do without spending a huge amount of time on fixes.
