### ISSUE TITLE
add link from website to demo

### ISSUE THREAD

**Issue by dhalperi** [uwescience/myria-website#7]

**Comment by dhalperi** [comment]
@ryanmaas  - @mbalazin asks that you look into this

**Comment by billhowe** [comment]
Maybe just make the big screenshot a link to the demo, as well as a little inline link somewhere.

**Comment by ryanmaas** [comment]
Ack, I missed this notification way back. I've added a link from the screenshot, as well as a "Demo" tab at the top of the page.
